### ISSUE TITLE
Fail to set default value for existing NULL rows on required DATE field

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#15]
### Actual behavior

When you set **required** on a field type date, if the table has entries, it asks you for a default value for existing NULL row. The update fail silently and the required attribute is not set.
### Step to reproduce
- Take an entity with existing rows containing a field type **DATE** (not required)
- update the field to set required
- set a default value
- it seems to work, but if you click again on the field, you see nothing has changed.

---
- Materia Server Version: 0.1.0
- Materia Designer Version: 0.1.0

**Comment by bumpmann** [comment]
Fixed
