### ISSUE TITLE
Lots of warning in the developer tools

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#22]
### Expected behavior

Clean these warnings
### Actual behavior

<img width="1018" alt="screen shot 2016-07-13 at 6 57 52 pm" src="https://cloud.githubusercontent.com/assets/1288646/16822622/c0e5082c-492b-11e6-9518-b8165572a33e.png">
### Step to reproduce the behavior

Navigate a bit in Materia designer

---
- Materia Server Version: 0.1.0
- Materia Designer Version: 0.1.0-rc.1

**Comment by bumpmann** [comment]
This is clean for 0.3 sep. release
