### ISSUE TITLE
After modifying a lots of files at the same time, Materia designer crash

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#24]
### Expected behavior

Materia designer should handle such modification.
### Actual behavior

After executing `npm install` or `bower install` or `git pull`, it crashes as it add/update lots of files simultaneously. It comes from watchers that seems to not be able to handle lots of files.
### Step to reproduce the behavior

`npm install` few packages while Materia Designer is open => it crashes instantly

---
- Materia Server Version: 0.1.0
- Materia Designer Version: 0.1.0-rc.2

**Comment by thyb** [comment]
Need to confirm if the fix for #25 fixes this issue too

**Comment by thyb** [comment]
Still crashing when lots of files are modified after a `npm install` because each file added/updated trigger a new mdToast.

We should just limit the number of mdToast displayed (3 toasts per second or something like that)

**Comment by bumpmann** [comment]
Fixed for 0.4
