### ISSUE TITLE
Watchers slow a lots the application in Windows

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#25]
### Expected behavior

Use https://github.com/Microsoft/vscode-filewatcher-windows to speed up watchers for Windows.
### Actual behavior

After installing few packages on bower in `web/` folder, the application crash as in #24 but it also slow a lot the application after the restart

As with FSEvent for Mac OS X, there is a native binary for Windows as used in Visual Studio Code: 
- https://github.com/Microsoft/vscode-filewatcher-windows
- https://github.com/Microsoft/vscode/tree/314e122b16c5c1ca0288c8006e9c9c3039a51cd7/src/vs/workbench/services/files/node/watcher/win32

---
- Materia Server Version: 0.1.1
- Materia Designer Version: 0.1.0-rc.2

**Comment by thyb** [comment]
fixed in 0.1.0-rc.3

**Comment by thyb** [comment]
0.1.0-rc.3 seems to introduce a new bug in Windows:

```
C:\Users\Jmarc\AppData\Local\materia\app-0.1.0-rc3\resources\app.asar\app\scripts\services\watcher.js:81 [FileWatcher] process error: Error: spawn app.asar\app\scripts\services\win32\CodeHelper.exe ENOENT_errorCallback @ C:\Users\Jmarc\AppData\Local\materia\app-0.1.0-rc3\resources\app.asar\app\scripts\services\watcher.js:81
localhost/bower_components/angular/angular.js:13708 ARIA: Attribute "

[FileWatcher] process error: Error: spawn app.asar\app\scripts\services\win32\CodeHelper.exe ENOENT_errorCallback 
@ C:\Users\Jmarc\AppData\Local\materia\app-0.1.0-rc3\resources\app.asar\app\scripts\services\watcher.js:81
localhost/bower_components/angular/angular.js:13708 ARIA: Attribute "
```

The packaged windows application doesn't find `CodeHelper.exe`

After this error, watchers just stop to work.

**Comment by bumpmann** [comment]
It seems that electron can't spawn exe from the asar archive, and electron-builder introduced some extra resources to not be packed with the asar (https://github.com/electron-userland/electron-builder/releases/tag/v5.16.0)

So i just added it as an extra resource, this should be OK in rc.4

**Comment by thyb** [comment]
after few tests on my friend's computer, it seems to work well! great :)
