### ISSUE TITLE
Lots of remove action don't ask for a confirmation

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#26]
### Expected behavior

Get a confirmation modal to be sure the user really want to remove a field/entity/relation/query.
### Actual behavior

When you remove something in Materia Designer, it doesn't ask for a confirmation.

It occurs with:
- remove a field
- remove an entity
- remove a relation
- remove a query

---
- Materia Server Version: 0.1.1
- Materia Designer Version: 0.1.0-rc.3

**Comment by bumpmann** [comment]
Ok for 0.3 sept release
