### ISSUE TITLE
Can't set % in query condition `field LIKE param`

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#3]
### Expected behavior

2 ways are implementable:
- make multiple LIKE operator (LIKE %param / LIKE %param% / LIKE param%)

or
- add 2 optional `%` on the left and on the right of the value/param => click toggle
### Actual behavior

<img width="418" alt="screen shot 2016-07-01 at 11 00 58 am" src="https://cloud.githubusercontent.com/assets/1288646/16525593/2877c82c-3f7b-11e6-8aee-eba19046f662.png">

There is no place where I can set a `%` character in the condition

---
- Materia Server Version: 0.1.0
- Materia Designer Version: pre-release

**Comment by jmarc-roy** [comment]
Since v1.0.0 % are automatically appended on left/right of the provided value.

**Comment by jmarc-roy** [comment]
Done in v1.0.1, if no joker characters ('%' or '_') are provided then '%' is automatically appended to left/right of the provided value, otherwise it will respect provided value.
