### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#30]
### Expected behavior

The same behavior than PostgreSQL but for SQLite
### Actual behavior

SQLite is not supported

---
- Materia Server Version: 0.1.3
- Materia Designer Version: 0.1.0

**Comment by bumpmann** [comment]
Sqlite has been added in https://github.com/webshell/materia-server/commit/e4d098bd8d201818b35e06080ce80f98f8b5aa42

**Comment by thyb** [comment]
Great! I rename this issue to support SQLite only (to be able to close this issue) and will re-open an issue for MySQL.

**Comment by thyb** [comment]
Ok, I forgot it also needs some fix in Materia designer to support SQLite. I re-open while we develop it.

**Comment by bumpmann** [comment]
This should be okay now
