### ISSUE TITLE
[Query relation] - Autocomplete parameters referencing a field of another entity 

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#37]
I have 2 entities: **article** and **comment** linked with the relation **belongsTo** (referenced with **id_article** field in the **comment** entity).

I want to search all comments for an article, so I will need to execute a **findAll** query on **comment** entity with the condition `id_article=:id_article`.

When I execute the query, I have to set the id_article myself.

It would be easier in Materia Designer to have an autocomplete/select component to choose fastly the article where I want to write the comment.

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by bumpmann** [comment]
Will be available in 0.3 (sept release)
