### ISSUE TITLE
Generate API endpoints for an entity

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#38]
### Expected behavior

It would enhance the UX to have a "Generate API endpoints for an entity".

When clicking on it:
- You can select an entity
- then it shows you all queries of this entity and a suggested URL for these queries
- You can validate, unvalidate each endpoint during the process
### Actual behavior

You have to add endpoint one by one using the endpoint builder.

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by jmarc-roy** [comment]
Done in v1.0.0. Ability to generate API endpoints when creating an entity.
