### ISSUE TITLE
Can't change field type

### ISSUE THREAD

**Issue by djunod** [materiahq/materia-designer-public#39]
### Expected behavior

Be able to change field type.
### Actual behavior

When changing a field type from text to number and then pressing Save, get the error message "Cannot set property 'type' of undefined.
### Step to reproduce the behavior

Create a Entity, add a field. Select the field and try to change the type.
BTW---Should be able to set type when you create the field.

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by thyb** [comment]
> BTW---Should be able to set type when you create the field.

I'm not sure to understand, you can't select the field type like in the gif animation of the tour ?

I've tried on Mac OS X with PostgreSQL and SQLite and it seemed to be working.

![try to reproduce](https://cloud.githubusercontent.com/assets/1288646/18372742/ccdc22ba-760c-11e6-9b25-c119cf5cdd26.gif)

Type casting are implemented here for postgresql: https://github.com/webshell/materia-server/blob/00e7c307d1c1a4cb88f774ca4761c0b0b4025128/lib/database/dialects/postgres.js#L193

Does this error happen with PostgreSQL or SQLite ?

You are on Windows or Mac OS X ?

**Comment by thyb** [comment]
I'm closing this issue as we haven't reproduced it. Don't hesitate to re-open it if this bug is still there.
