### ISSUE TITLE
Application Files Bar not Updated with New Files

### ISSUE THREAD

**Issue by beauremus** [materiahq/materia-designer-public#40]
### Expected behavior

Application files right bar refresh with new files when created.
### Actual behavior

After having Materia generate static files, none showed up in the application files bar.
### Step to reproduce the behavior

Using Windows 10
Start a new project
Use website menu on left to create static files
Navigate to Overview
Nothing is updated
## FYI I can see from Windows explorer that the files DO exist
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by thyb** [comment]
I've just tested on Windows and reproduced the bug. 

The normal behavior (taken from the Mac OS X version) is the following:

![watchers](https://cloud.githubusercontent.com/assets/1288646/18407427/6a260604-76de-11e6-9d33-4cc039195768.gif)

This bug has been added to the [September release](https://github.com/webshell/materia-designer/milestone/4) milestone.

**Comment by bumpmann** [comment]
Ok for materia 0.3 sept release (very soon)
