### ISSUE TITLE
Help Menu Leads to http://electron.atom.io/

### ISSUE THREAD

**Issue by beauremus** [materiahq/materia-designer-public#41]
### Expected behavior

Something helpful?
### Actual behavior

Opens browser pointed at http://electron.atom.io/
### Step to reproduce the behavior

Click Help>Learn More

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by bumpmann** [comment]
Thanks, this will be changed in the next version.
