### ISSUE TITLE
Global search never matches any documents

### ISSUE THREAD

**Issue by ariroseonline** [materiahq/materia-designer-public#42]
### Expected behavior

In the global search, I expect a search to match entities, api endpoints, file names, etc.
### Actual behavior

 It never matches anything.
### Step to reproduce the behavior

Create some entities, and some api endpoints, and then type anything into global search :)

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by bumpmann** [comment]
It seems that is happening on windows versions, i ll take a look at it.

**Comment by ariroseonline** [comment]
FYI: I am using the Mac version.

**Comment by thyb** [comment]
Materia is indexing Entities/Queries and Endpoints using [lunr](http://lunrjs.com/). We don't index files yet but it's something we're likely to implement soon.

The following animation is the use case we've tested:

![search](https://cloud.githubusercontent.com/assets/1288646/18406665/cd85fc2e-76cd-11e6-8d9d-95ce75d24044.gif)

Do you have something which differ from the animation ? If yes and if you still can't match any search results, can you open the developer tools (view => toggle developer tools) and tell us if you have any Javascript error in the console?

**Comment by ariroseonline** [comment]
Interesting. I just rebooted the app after a day off of it. And it now works as you describe. 
So sorry for the issue, it does seem to work! 

However, I did a test to see if that I added an entity in this new session,  would it be indexed by the search. It turns out it doesn't. I suppose it is still an inconvenience to not know why the global search isn't indexing during a working session when you create endpoints and entities. This is particularly strange during your initial use of the app when nothing returns from search.

**Comment by thyb** [comment]
Ah yes, you're right! It's not indexing new Entity/Query/Endpoint.

I have opened the issue https://github.com/webshell/materia-designer/issues/44 for the bug you've explained.
I've also opened  https://github.com/webshell/materia-designer/issues/45 for indexing files too in the search engine.

Both issues have been added to the [September release](https://github.com/webshell/materia-designer/milestone/4) milestone.

Thanks for pointing out these bug/enhancement.
