### ISSUE TITLE
New entity, query, endpoint and files are not indexed in the search engine

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#44]
### Expected behavior

It should index new File, Entity, Query and endpoint when they are added. 
### Actual behavior

They are not added to the index of the search engine
### Step to reproduce the behavior
- Create a new application
- Create an entity "test"
- Search for "test" => no result

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by bumpmann** [comment]
Done for 0.3 (sept. release)
