### ISSUE TITLE
Association table's primary keys from a belongsToMany relation should be the PK of the source tables or at least be editable

### ISSUE THREAD

**Issue by jmarc-roy** [materiahq/materia-designer-public#46]
### Expected behavior

Association table's primary keys from a belongsToMany relation should be the PK of the source tables or at least to be editable
### Actual behavior

PKs in the association table are "PK from source table + entityName" and are not editables
### Step to reproduce the behavior

Open materia-designer create 2 entities and then a belongsToMany relationship

---
- Materia Server Version: 0.1.0
- Materia Designer Version: 0.1.0

**Comment by thyb** [comment]
It has been fixed previously (v0.3 - September release)
