### ISSUE TITLE
No delete cascade on SQLite

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#47]
### Expected behavior

Like on PostgreSQL, if you delete a row containing associated data (hasMany/belongsTo), it should also removed the associated data in cascade.
### Actual behavior

It throws an error:

```
{"error":true,"message":"SQLITE_CONSTRAINT: FOREIGN KEY constraint failed"}
```
### Step to reproduce the behavior
- Create an entity **article** and an entity **comment**
- Link these entity as "article has many comments"
- Create an article and a comment for this article
- Try to delete the article => error

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by thyb** [comment]
Same issue in SQLite for update cascade.

As explained here: http://stackoverflow.com/questions/5890250/on-delete-cascade-in-sqlite3

> Foreign key support is not enabled in SQLite by default. You need to enable it manually each time you connect to the database using the pragma:
> `PRAGMA foreign_keys = ON`

SQLite reference about this: https://www.sqlite.org/foreignkeys.html#fk_enable

**Comment by bumpmann** [comment]
Ready for 0.5
