### ISSUE TITLE
Local connections

### ISSUE THREAD

**Issue by lifeiscontent** [materiahq/materia-designer-public#48]
### Expected behavior

To work fast
### Actual behavior

Works very slow
### Step to reproduce the behavior
1. Come to Ho Chi Minh City, Vietnam
2. Try to use Materia Designer
3. Cry because of how slow it is.

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by thyb** [comment]
We've made Materia Designer as a Desktop application with the offline capability in mind. You don't need any internet connection to run Materia Designer so I don't think there's a link with the location.

Can you tell us more about what's your OS ? and do you have any error in the Developer tools? (Menu: View => Toggle Developer tools)

**Comment by lifeiscontent** [comment]
@thyb using Mac OSX 10.11.6 I've since removed the app, but as soon as I get a chance to play with it again, I'll update you on the developer tools stuff.
