### ISSUE TITLE
 Rename a field related to a relationship leads to the lost of the relationship

### ISSUE THREAD

**Issue by jmarc-roy** [materiahq/materia-designer-public#52]
### Expected behavior

We should be able to rename a field related to a relationship, without destroying relationships.
### Actual behavior

When we rename a field related to a relationship, the relationship is lost, because the new name of the field is not updated in the related entities json files.
The console gives the following : 

```
WARNING: In **table2**: The relation's referenced field **table2.table1_id** if does not exist. Skipped relation
```
### Step to reproduce the behavior

Start Materia Designer, create a relationship and rename the primaryKey field participating in a relationship.

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by bumpmann** [comment]
This should be ok since webshell/materia-server@a12dbfd8d53f11a0fb10675dcf9590a75437d6a6 and will be available on 0.3 (sept release)
