### ISSUE TITLE
File editing does not temporarily save changes

### ISSUE THREAD

**Issue by darioncassel** [materiahq/materia-designer-public#53]
### Expected behavior

When editing files in the "Overview" section of the app, if a user makes a change to a file and then switches to a different file, their changes should be temporarily saved rather than discarded as they would be in a multi-tab text editor. Alternatively, a user could receive some sort of warning when navigating away from a file to alert them that their changes haven't been saved.
### Actual behavior

Currently, when switching between files or leaving the "Overview" area, any unsaved changes are lost without warning.
### Step to reproduce the behavior
1. Open a file for editing in the "Overview" section.
2. Make some changes but don't save them.
3. Switch to a different file.
4. Switch back to the previous file, the unsaved changes will be gone.

---
- Materia Server Version: 0.2.2
- Materia Designer Version: 0.2.2

**Comment by thyb** [comment]
Thanks for the feedback, I totally agree. This issue is related with #26.

**Comment by darioncassel** [comment]
No problem :) Thanks for all the work you've put into the product so far. I enjoy using it.

**Comment by bumpmann** [comment]
Not really related with #26 if the expected behaviour is to keep the changes in memory. I ll check it

**Comment by bumpmann** [comment]
This is fixed for 0.3 sept release. Until we have something like a multi tab editor, i just added a confirmation with save / don't save / cancel if there's a change.
