### ISSUE TITLE
Rename query create a duplicate query

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#55]
### Current behavior

When I rename a query, I get 2 queries:
- One with the old name (and old config)
- One with the new name (and the new config)
### Expected behavior

It should remove the duplicate (old) query
### Step to reproduce the behavior
- Create a query (i tried with a Javascript query)
- Then once the query is created, go back in the query builder to edit this query, change the query name and save => there is 2 query, one with the old name and one with the new name

---
- Materia Server Version: 0.3.0
- Materia Designer Version: 0.3.0

**Comment by bumpmann** [comment]
Fixed for 0.4
