### ISSUE TITLE
Javascript query params are different if they are used in Materia designer or via the API

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#57]
### Current behavior

The second parameters of the exported function is ambigous when creating a Javascript query:

```
module.exports = (model, req, app) => {
}
```

it's effectively the node.js `req` when you execute the query in an endpoint. So, to retrieve param **test** in a GET endpoint, you would use `req.params.test`.

But... if you execute it as a query from Materia designer, the parameters are directly sent in req object so you would use `req.test` directly.

To workaround this issue, I redeclare my inputs as follow in all my js endpoints:

```
module.exports = (model, req, app) => {
    let test = req.test || req.params.test
    ...
}
```
### Expected behavior

To have params/inputs directly in the root of the object :

```
module.exports = (model, params, app) => {
    //use req.test directly
}
```

If the query is called from a GET endpoint, `params` is `req.params`

If the query is called from a endpoint (other than GET), `params` is `MERGE(req.params, req.body)` (`req.body` overloads `req.params`) 
### Step to reproduce the behavior
- call a Javascript query with a param **test** => `req.test` is needed to access the param
- call a Javascript query from a GET endpoint => `req.params.test` is needed to access the param

---
- Materia Server Version: 0.3.0
- Materia Designer Version: 0.3.0

**Comment by thyb** [comment]
Delayed to november release as it will be done with #60 (expected for november release too).

**Comment by bumpmann** [comment]
Ready for 0.5
