### ISSUE TITLE
Enhancement of a Materia application structure

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#60]
### Current behavior

Currently a Materia application looks like:

```
myApp/
|  addons/
|  |  user-management/
|  |  |  ...
|  |  payment/
|  |  |  ...
|  entities/
|  |  queries/
|  |  |  ...
|  |  entity1.json
|  |  entity2.json
|  web/
|  |  scripts/
|  |  |  ...
|  |  index.html
|  api.json
|  database.json
|  materia.json
|  server.json
```
### Expected behavior

It would be more conventional to have a structure like the following:

``` myApp/
|  client/
|  |  dist/
|  |  |  index.html
|  |  |  main.js
|  |  |  ...
|  |  src/
|  |  gulpfile.js
|  |  ...
|  server/
|  |  addons/
|  |  controllers/ =>instead of endpoints/
|  |  |  main.ctrl.js
|  |  |  user.ctrl.js
|  |  |  ...
|  |  models/ => instead of entities/
|  |  |  |  queries/
|  |  |  |  |  ...
|  |  |  entity1.json
|  |  |  ...
|  |  api.json
|  |  database.json
|  |  server.json
|  package.json
|  .gitignore
```

It would ease the discoverability of a new Materia application with a better separation of concerns.

It would also let more place at the root folder to create and maintain a gulpfile/gruntfile, node packages, tests, tool scripts, documentation etc.

The list of actions to make this change:
- [x] Load files from their new location
- [x] Save files to their new location
- [x] Allow multiple endpoints definition per controller file in `server/controllers/`
- [x] Allow multiple queries definition per file in `/server/models/queries/`
- [x] Generic package.json to install everything in `client/` and `server/`
- [x] Migration tool to move easily from old architecture to new architecture

---
- Materia Server Version: 0.3.0
- Materia Designer Version: 0.3.0

**Comment by bumpmann** [comment]
After some brainstorming we got this structure :

```
|  web/    <-- configurable path but web/ by default so that client/dist and src are still valid
|  |  index.html
|  |  main.js
|  |  ...
|  server/
|  |  // removed addons/ and use npm scoped modules instead
|  |  controllers/ =>instead of endpoints/
|  |  |  main.ctrl.js
|  |  |  user.ctrl.js
|  |  |  ...
|  |  models/ => instead of entities/
|  |  |  |  queries/
|  |  |  |  |  ...
|  |  |  entity1.json
|  |  |  ...
|  |  api.json
|  |  // database.json remove since materia 0.4.0
|  |  server.json
|  package.json // materia.json is just an object in package
|  .gitignore
```

**Comment by bumpmann** [comment]
Ready for 0.5
