### ISSUE TITLE
Unable to execute create query

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#63]
Can someone please explain how to execute a create query with multiple params. I can't seem to find any documentation on that.

---
- OS Platform MacOS
- Database : PostgreSQL
- Materia Server Version: 0.3.2
- Materia Designer Version: 0.3.2

**Comment by thyb** [comment]
You're right, the documentation is a little light yet, we're working to improve it for the October release (v0.4).

The easiest way to execute a create query:
- Create a endpoint (in the API section) to link your query to it.
- In your frontend, you can make an HTTP call with the parameters in body parameters to execute the query

You can take a look at the [TODO sample application](https://github.com/thyb/materia-todo) to see a possible implementation with Angular 1.x (we're using the create query to create new todo)

If you've setup your create query to run on "/create", with jquery, you can execute it like the following:

``` js
$.post('/api/create', {
     param1: 'value',
     param2: 'value2'
}).success(function() {
     //todo when it's done
});
```

The parameters correspond to the input defined in the query builder.

If you need other explanation, don't hesitate, I'll try to guide as much as I can.
