### ISSUE TITLE
Query/endpoint builder (type Javascript) did not reload the content when the file is modified

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#65]
### Current behavior

If you modify a file being open in the query builder or the endpoint builder (Type javascript only). The builder wont reload the modified code.

### Expected behavior

The builder should subscribe `updateFile` event to reload the file when needed.

### Step to reproduce the behavior

* Open the endpoint builder on an endpoint type Javascript.
* Update the file in an editor (outside materia designer)
* Go back to materia designer => the content of the endpoint builder is not refreshed

---

* OS Platform / arch: All
* Database : All
* Materia Server Version: 0.3.2
* Materia Designer Version: 0.3.2

**Comment by jmarc-roy** [comment]
Done in v1.0.0. Latest file version is always displayed when opening the endpoint builder.
