### ISSUE TITLE
How would I go about uploading a file?

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#69]
I am trying to upload an image, I can't seem to upload a file because I need a server side script to actually write the file to the server. The other option is to save the base 64 image to the server, which gives me a 413 Error. Any ideas?

**Comment by GeoAstronaute** [comment]
Hi TerryBearDash,
You can already code your server-side script in a javascript endpoint. All you need is to install node-modules you need in you application folder and require them in your endpoint. For example I use flow.js to upload files client-side and use a node script for the server find here : [https://github.com/flowjs/flow.js/blob/master/samples/Node.js/flow-node.js](url).
The code in my endpoint look like that :

**Comment by jmarc-roy** [comment]
Hi TerryBearDash,
You can make a javascript endpoint to develop features like file uploads.
 All you need is to install NPM packages you need, in your application folder, and require them in your endpoint. 
For example I use flow.js client side and a node js script found in their sample code (here : [https://github.com/flowjs/flow.js/blob/master/samples/Node.js/flow-node.js](url)). The code in my javascript endpoint look like that : 

``` js
module.exports = (req, app, res) => {
    var multipart = require('connect-multiparty');
    var multipartMiddleware = multipart();
    var flow = require('../custom_node_modules/flow-node.js')('tmp') //not on NPM
    var fs = require('fs')
    multipartMiddleware(req, res, (newReq, newRes) => {
        flow.post(req, function (status, filename, original_filename, identifier) {
            var stream = fs.createWriteStream(app.path + '/img/' + identifier);
            if (status == 'done') {
                flow.write(identifier, stream);
            }
        })
    })
}
```

As you see I use NPM packages, and a middleware, my files are sent to the /img folder of my application project.
With the same idea you can use other libraries to achieve your upload.

Hope it can help!

**Comment by thyb** [comment]
I haven't found the time to test this case yet, but as @GeoAstronaute said: it should work using a Javascript Endpoint and the NPM library you prefer.

I would advise tu go with [Multer](https://github.com/expressjs/multer) as it's a maintained library (available on NPM) made by the Express team. As Materia Server has been made on top of Express, it should work just fine. I'm going to make a working demo after the November release.

We've planned to make a File & Image field type (https://github.com/webshell/materia-server/issues/7) in the future (for the January release if everything goes well) which would handle this use case and upload in the location you configured. I would like to let the possibility to configure the upload location to a folder within your application directory or in a Amazon S3 instance to let you scale easily.

**Comment by bumpmann** [comment]
Using multer i use this:

```javascript
const multer  = require('multer')

module.exports = class UploadCtrl {
    constructor(app) {
        this.app = app;
        this.upload = multer({ dest: app.path + '/web/uploads/' })
    }
    uploadAvatar(req, res, next) {
        this.upload.single('avatar')(req, res, () => {
            // req.file is the `avatar` file
            // req.body will hold the text fields, if there were any
            res.send("ok")
        })
    }
}
```

**Comment by TerryBearDash** [comment]
Guys I am just not getting this right, is there anyone willing to maybe have a chat on skype and just give me some guidance?

These are the errors that I keep getting.

```
Toast info: Error while setting endpoint: Could not load controller upload
Error origin: Error: Cannot find module '/node_modules/multer'

 - reset-search-paths.js:35 Function.Module._resolveFilename
/Applications/Materia Designer.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12

 - module.js:20 require
internal/module.js:20:19

 - upload.ctrl.js:1 Object.<anonymous>
/server/controllers/upload.ctrl.js:1:94

 - module.js:20 require
internal/module.js:20:19

 - endpoint.js:24 Controller.load
[app.asar]/[materia-server]/dist/lib/api/endpoint.js:24:30

 - endpoint.js:62 new Endpoint
[app.asar]/[materia-server]/dist/lib/api/endpoint.js:62:18

 - api.js:41 Api.add
[app.asar]/[materia-server]/dist/lib/api.js:41:23
```

###############################################

This is the endpoint that I am trying to add

```js
var multer  = require('/node_modules/multer')

class UploadCtrl {
    constructor(app) {
        this.app = app; 
        this.upload = multer({ dest: app.path + '/web/uploads/'})
    }

    postUploader(req, res, next) {
        this.upload.single('profile')(req, res, () => {
            console.log('error');
        })
    }
}

module.exports = UploadCtrl;
```

**Comment by thyb** [comment]
To install multer, run in the console: `npm install multer` in your application directory

Then in line 1, replace the line by: `var multer = require('multer')`

To discuss with us, you can join our [Slack channels](https://materia-slack-invite.herokuapp.com/)

**Comment by bumpmann** [comment]
You can also take a look at my test app for upload : https://github.com/bumpmann/materia-simple-upload
