### ISSUE TITLE
Addons installation enhancement

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#74]
### Current usage

`npm install {addonPackage} --save`

### Issues

1- `--save` is mandatory as Materia Designer watch the `dependencies` key in `package.json` to discover addons
2- Impossible to setup an addon after the installation from the CLI without configure manually the `package.json` in `materia.{addonName}`
3- Same as #73 - If an addon require an APIKey as setting (e.g. Stripe addon / Emailing Addon with sendgrid) and if the application is opensource, these APIKey will be published on Github.

### Solution

1/ & 2/ Wrap the `npm` call in `materia install {addonPackage}`. The `{addonPackage}` can be a npm package or a local directory (for addons development). After the installation, `materia install` will read the `setup.json` file in the addons folder which describe the configuration steps.

e.g.
```
$ materia install @materia/user-management
Installing... DONE
Configuration...
Do you want to allow anonymous users to signup ? [Y/N]: Y
Do you want to enable user roles ? [Y/N]: Y
What social connect do you want enable ? (optional, space separated) [facebook/twitter/google]: facebook google

Installation and configuration of '@materia/user-management' was successful.
```

3/ Move the addon configurations in `.materia/addons.json`
The discovery of an addon in Materia Designer could be done using this file.

---

* Materia Server Version: 0.5.1
* Materia Designer Version: 0.5.0

**Comment by bumpmann** [comment]
Ok for the 3/

But for 1/ and 2/: I think we should add `materia setup [addPackage]` so that we can still configure the addon(s) after a npm install. This way, we should make {addonPackage} optional so that `materia install` could run `npm install` + `materia setup` and `materia install {addonPackage}` run `npm install {addonPackage} --save` + `materia setup {addonPackage}`

**Comment by ThinkDevStudios** [comment]
Guys. Where can i find the list of available addons for materia designer?

**Comment by bumpmann** [comment]
Hi, as you can see this is still experimental and we re still fixing / enhance the addons system while developing some basic ones (user management, emailing...). I hope this will be ready for the next release.
