### ISSUE TITLE
Enhance files/folder management in Overview

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#75]
The button to create file has been removed in v0.4 as the UI was not intuitive.

- [x] Remake this feature using an UI like VSCode or Atom (inline edition)
- [x] Drag and drop file/folder to move

Enable context menu to:

- [x] Create file
- [x] Create folder
- [x] Rename
- [x] Delete

---

* Materia Server Version: 0.5.1
* Materia Designer Version: 0.5.0

**Comment by bumpmann** [comment]
Any idea for the drag&drop thing ? I tried with angular-drag-and-drop-lists but couldn't get anything  move

**Comment by bumpmann** [comment]
I removed "Move" from the context menu as it is possible with drag&drop

**Comment by bumpmann** [comment]
Ready for next release.
