### ISSUE TITLE
Error trying to add relation

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#76]
I try to add a relation between 2 entities then I get the error - Invalid input syntax for integer: ""

My developer tools produces this error:

Toast info: invalid input syntax for integer: ""
/Applications/Materia Designer.app/Contents/Resources/app.asar/app/scripts/services/toaster.js:48 Error stack: SequelizeDatabaseError: invalid input syntax for integer: ""

 - query.js:357 Query.formatError
[app.asar]/[sequelize]/lib/dialects/postgres/query.js:357:14

 - query.js:88 Query.<anonymous>
[app.asar]/[sequelize]/lib/dialects/postgres/query.js:88:19

 - query.js:133 Query.handleError
[app.asar]/[pg]/lib/query.js:133:8

 - client.js:180 Connection.<anonymous>
[app.asar]/[pg]/lib/client.js:180:26

 - connection.js:121 Socket.<anonymous>
[app.asar]/[pg]/lib/connection.js:121:12

toast @ /Applications/Materia Designer.app/Contents/Resources/app.asar/app/scripts/services/toaster.js:48

---

* OS Platform / arch: Windows x64 / MacOS
* Database : MySQL / PostgreSQL / SQLite
* Materia Server Version: 0.5.1
* Materia Designer Version: 0.5.0

**Comment by thyb** [comment]
Thanks for the feedback, we've just reproduced this regression. It occurs only with PostgreSQL. We're adding some tests and will fix this issue for the next release (in few days).

**Comment by jmarc-roy** [comment]
Hi TerryBearDash,
Pending the next release, you can work around the problem by adding at least one row on your source table for a 1-n relationship (no problem with n-n relationships). 
For example if you have a project table and a user table, you will have to add at least one project, in the case  "one project has many users", for your relationship to be successfully created.
Hope it help!

**Comment by bumpmann** [comment]
Fixed for the 0.6 release
