### ISSUE TITLE
Uploading an image

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#77]
Guys I am just not getting this right, is there anyone willing to maybe have a chat on skype and just give me some guidance?

These are the errors that I keep getting.

Toast info: Error while setting endpoint: Could not load controller upload
Error origin: Error: Cannot find module '/node_modules/multer'

reset-search-paths.js:35 Function.Module._resolveFilename
/Applications/Materia Designer.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12

module.js:20 require
internal/module.js:20:19

upload.ctrl.js:1 Object.
/server/controllers/upload.ctrl.js:1:94

module.js:20 require
internal/module.js:20:19

endpoint.js:24 Controller.load
[app.asar]/[materia-server]/dist/lib/api/endpoint.js:24:30

endpoint.js:62 new Endpoint
[app.asar]/[materia-server]/dist/lib/api/endpoint.js:62:18

api.js:41 Api.add
[app.asar]/[materia-server]/dist/lib/api.js:41:23

###############################################

This is the endpoint that I am trying to add

`var multer = require('/node_modules/multer')

class UploadCtrl {
constructor(app) {
this.app = app;
this.upload = multer({ dest: app.path + '/web/uploads/'})
}

postUploader(req, res, next) {
	this.upload.single('profile')(req, res, () => {
	    console.log('error');
	})
}
}

module.exports = UploadCtrl;`

**Comment by thyb** [comment]
I replied in #69. I close this one as it's a duplicate.
