### ISSUE TITLE
Impossible to remove a endpoint parameter

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#78]
### Step to reproduce the behavior

* Create a Javascript endpoint with parameters
* Try to remove a param => No error but the param is not removed

---

* OS Platform / arch: Windows x64 / MacOS
* Database : MySQL / PostgreSQL / SQLite
* Materia Server Version: 0.6.0
* Materia Designer Version: 0.6.0

**Comment by jmarc-roy** [comment]
Fix in v1.0.0
