### ISSUE TITLE
Crash when the application folder is renamed/removed

### ISSUE THREAD

**Issue by thyb** [materiahq/materia-designer-public#8]
### Expected behavior

It should display an error: **The application has been moved or removed. Please select the new location for this application.**

When the user click on this error, a form with a folder-input should be displayed to let the user select the new path. Also, the user should be able to remove the app.
### Actual behavior

After renaming an application folder, Materia display an empty row in the application list. If the user click on it, it crash Materia designer.

![screen shot 2016-07-03 at 4 18 31 am](https://cloud.githubusercontent.com/assets/1288646/16544471/5fa440ae-40d5-11e6-8706-f2ce6e81f659.png)

Then, if we click on the blank row:

![screen shot 2016-07-03 at 4 17 35 am](https://cloud.githubusercontent.com/assets/1288646/16544466/23d5d0ce-40d5-11e6-84da-4ca63647bdff.png)

with this error in the inspector console:

```
angular.js:13236 TypeError: $rootScope.app.load is not a function

 - index.js:26 new DashboardCtrl
/Users/thyb/projects/materia-es6/materia-designer/src/app/scripts/controllers/dashboard/index.js:26:18

(...)
```
### Step to reproduce the behavior
- create an app
- rename the app folder using the CLI: `mv my-app my-app2`
- restart materia designer

---
- Materia Server Version: 0.1.0
- Materia Designer Version: pre-release

**Comment by thyb** [comment]
It also occurs when you create an application with a wrong path (e.g. `toto` instead of `~/toto`)

**Comment by bumpmann** [comment]
Fixed
