### ISSUE TITLE
Socket.io?

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#82]
Hi guys,

Does anybody have an idea on how to get socket.io or similar socket plugin to work inside materia? I tried but simply can't seem to get the server side to respond as it should. Any assistance would be greatly appreciated.

**Comment by jmarc-roy** [comment]
Hi @TerryBearDash,

As you’ve discussed with @thyb, I made a socket.io addon for Materia Desginer a few months ago, but it wasn't perfect. 

I just released v0.2.1 from this addon with the new release of Materia Designer v0.8.0. 
I made a Gif to show how it works : 
![materia-socketio-addon](https://user-images.githubusercontent.com/14280160/28312160-75311ad8-6bb2-11e7-9d5f-c11730e49280.gif)

Hope you will enjoy it.
