### ISSUE TITLE
Impossible to install addon

### ISSUE THREAD

**Issue by MBuffenoir** [materiahq/materia-designer-public#83]
### Current behavior
Clicking on the install button in the Addons panel end up with the following message:
`Failed to install/uninstall addons`

### Expected behavior
Addon installation
### Step to reproduce the behavior
On a mac with version 0.7 > click on the mailjet addon install button.
---

* OS Platform / arch: Windows x64 / MacOS
MacOS
* Database : MySQL / PostgreSQL / SQLite
SQLite
* Materia Server Version: 0.7.1
* Materia Designer Version: 0.7.0

**Comment by thyb** [comment]
I have started to fix it which should be released tonight or tomorrow:
https://github.com/webshell/materia-server/commit/46f848052a7ea28efa0b7e1f85619b3ab07e4c21

In the meantime, you can install addons using the CLI with `npm` or `yarn` e.g. for mailjet:
`npm install @materia/mailjet --save` (don't forget the --save as Materia uses `package.json` to detect Materia addons)
or (using yarn)
`yarn add @materia/mailjet`

then, once an addon installed, restart Materia Designer (view => reload).

All existing addons are listed here: https://www.npmjs.com/~materia

**Comment by MBuffenoir** [comment]
Thanks for the quick reply !

I runned it in the project folder and it seemed to have worked perfectly 👍 . Will try your users modules also.

First time I ever try to code an app with a GUI, interesting concept, will continue to explore for sure :-) and give you feedback.

**Comment by thyb** [comment]
We've published yesterday the July release - v0.8 which fix this issue. See the release note: https://getmateria.com/releases

Unfortunately, the auto updater won't work to upgrade from v0.7 to v0.8, so you need to download the new version manually from https://getmateria.com - the auto updater will work better at the next release !
