### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#84]
Hi guys, 

Could anyone please assist me with launching my app on a centos linux server. 

I am able to start the materia server without any issues, but just can't seem to get it to render on my server ip. 

Any help would be greatly appreciated.

**Comment by jmarc-roy** [comment]
Hi @TerryBearDash ,

Please check this steps :
- Make sure you have materia-server installed globally ("npm install materia-server -g") on your server
- Make sure, that your file 'server.json' in ./materia folder of your application, is correctly set with your production settings. Here is an example, with a Postgres database : 
```
{
	"dev": {
		"web": {
			"host": "localhost",
			"port": 8080
		},
		"database": {
			"type": "postgres",
			"host": "localhost",
			"port": 5432,
			"database": "your_developppement_database_name",
			"username": "postgres",
			"password": "your_developpement_database_password"
		}
	},
     "prod": {
		"web": {
			"host": "your_server_ip",
			"port": 80
		},
		"database": {
			"type": "postgres",
			"host": "localhost",
			"port": "5432",
			"database": "your_production_database_name",
			"username": "postgres",
			"password": "your_production_database_password"
		}
     }
}
```
- Don't forget to start materia in production mode ("materia start --mode=prod")

With all this steps, it should work.

**Comment by TerryBearDash** [comment]
It works, thank you very much!
