### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by TerryBearDash** [materiahq/materia-designer-public#86]
Hi Guys,

How do I go about adding a SSL Certificate to my materia production environment.

**Comment by TerryBearDash** [comment]
On a linux server.

**Comment by TerryBearDash** [comment]
@GeoAstronaute @thyb any feedback on this yet?

The reason I am asking for the SSL on a normal linux server, is - my app has video upload functionality, which is severely limited on google cloud, (10mb is the HTTP request and response size limit) - the other issue is, when you upload 3 X 20mb videos (hard limit of about 30mb) immediately after each other they successfully upload, but then because I am using multer memory Storage as per the google docs, then my VM instance crashes and my site shuts down for about 10 minutes, - so you can understand my frustration.

All this can be sidetracked if I can just setup a ssl certificate on a normal linux server.

**Comment by thyb** [comment]
Currently, it's not possible to configure SSL directly in Materia Server. But you can use Nginx or another webserver which support reverse proxy and SSL.
Take a look at this link: https://www.sitepoint.com/configuring-nginx-ssl-node-js/
Once Nginx configured, you can edit your server.json file and add `ssl: true` to the production server settings.
